USE Chocolate_sales;

-----Q1 - How many total orders are recorded in the sales table?
SELECT COUNT( *) AS Total_orders
FROM sales;

-----Q2 - List all unique product categories from the products table.
SELECT DISTINCT category
FROM products;

-----Q3 - How many customers are registered in the dataset?
SELECT COUNT(*) AS Total_customers
FROM customers;

-----Q4 - List all stores and the cities they are located in.
SELECT store_name, city
FROM stores;

-----Q5 - Which products have a cocoa percentage greater than 70%?
SELECT product_name, cocoa_percent
FROM products
WHERE cocoa_percent > 70;

-----Q6 - How many products does each brand offer? List brands and their product count.
 SELECT brand,
       COUNT(*) AS product_count
FROM products
GROUP BY brand
ORDER BY product_count DESC;

-----Q7 - Find all sales where a discount was applied (discount > 0).
SELECT *
FROM sales
WHERE discount > 0;

 
-----Q8 - What is the total revenue generated across all sales?
SELECT SUM(revenue) AS total_revenue
FROM sales;



-----Q9 - What is the total profit made from all orders?
SELECT SUM(profit) AS total_profit
FROM sales;

-----Q10 - What is the minimum and maximum profit from a single order?
SELECT MIN(profit) AS min_profit,
       MAX(profit) AS max_profit
FROM sales;

-----Q11 - What is the total quantity sold per product category? (Join sales and products)
SELECT p.category,
       SUM(s.quantity) AS total_quantity_sold
FROM sales s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.category;


-----Q12 - Show the store name, city, and total revenue for each store. (Join sales and stores)
SELECT st.store_name,
       st.city,
       SUM(s.revenue) AS total_revenue
FROM sales s
JOIN stores st
ON s.store_id = st.store_id
GROUP BY st.store_name, st.city;




-----Q13 - Which brand generates the highest total profit? (Join sales and products)
SELECT TOP 1 p.brand, SUM(s.profit) AS total_profit
FROM sales s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.brand
ORDER BY total_profit DESC;

-----Q14 - Which country generates the most total revenue? (Join sales and stores)
SELECT TOP 1 st.country, SUM(s.revenue) AS total_revenue
FROM sales s
JOIN stores st
ON s.store_id = st.store_id
GROUP BY st.country
ORDER BY total_revenue DESC;

-----Q15 - What is the total revenue generated by loyalty members vs non-loyalty members? (Join sales and customers)
SELECT c.loyalty_member, SUM(s.revenue) AS total_revenue
FROM sales s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.loyalty_member;

-----Q16 - List the top 5 products by total quantity sold, including the product name and brand.
SELECT TOP 5 p.product_name, p.brand, SUM(s.quantity) AS total_quantity_sold
FROM sales s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.product_name, p.brand
ORDER BY total_quantity_sold DESC;


-----Q17 - Which store type (retail, online, etc.) generates the most revenue?
SELECT st.store_type, SUM(s.revenue) AS total_revenue
FROM sales s
JOIN stores st
ON s.store_id = st.store_id
GROUP BY st.store_type
ORDER BY total_revenue DESC;


-----Q18 - What is the average order revenue for male vs female customers? (Join sales and customers)
SELECT c.gender,
       AVG(s.revenue) AS average_order_revenue
FROM sales s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.gender;


-----Q19 - Which city has the highest number of orders placed? (Join sales and stores)
SELECT TOP 1 st.city, COUNT(*) AS total_orders
FROM sales s
JOIN stores st
ON s.store_id = st.store_id
GROUP BY st.city
ORDER BY total_orders DESC;


-----Q20 - List the products that have a unit price greater than the average unit price across all products. (Use a subquery)
SELECT DISTINCT p.product_name, s.unit_price
FROM sales s
JOIN products p
ON s.product_id = p.product_id
WHERE s.unit_price >
(
    SELECT AVG(unit_price)
    FROM sales
)
ORDER BY s.unit_price DESC;
